### ISSUE TITLE
Looks like new Php version needed

### ISSUE THREAD

**Issue by virenderscideas** [lorisleiva/artisan-ui#1]
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )

Composer version 2.0.7 2020-11-13 17:31:06

![image](https://user-images.githubusercontent.com/65526033/122099956-3c477480-ce30-11eb-8526-d6378896e271.png)

**Comment by saineshmamgain** [comment]
@virenderscideas this package works on php ^8.0

**Comment by ousid** [comment]
This Package requires only`PHP ^8.0`
https://github.com/lorisleiva/artisan-ui/blob/24fb3251482ca78d6cedf4dc093c4531eb24535e/composer.json#L20
